diplom_work/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found
from django.conf.urls.static import static

from diplom_work import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]
handler404 = page_not_found

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', main, name='main'),
    path('multicookers', multicookers, name='multicookers'),
    path('mobile_phones', mobile_phones, name='mobile_phones'),
    path('fridge/<int:_id>/', fridge, name='fridge'),
    path('mobile_phone/<int:_id>/', mobile_phone, name='mobile_phone'),
    path('multicooker/<int:_id>/', multicooker, name='multicooker'),
    path('search/', search, name='search'),
    ]

main/models.py
from django.db import models
from django.db.models import CharField
from django.urls import reverse


class Fridge(models.Model):  # Холодильники
    title = models.TextField(blank=False, null=False, verbose_name='Название')
    img_url = models.TextField(null=True, blank=True, verbose_name='Ссылка на картинку')

    # Характеристики
    @property
    def fields(self):
        return [f.name for f in self._meta.fields + self._meta.many_to_many]

    def get_absolute_url(self):
        return reverse('fridge', kwargs={'_id': self.pk})

    @property
    def fields_verbose(self):
        return dict([(f.name, f.verbose_name) for f in self._meta.fields + self._meta.many_to_many])
    total_useful_volume = CharField(null=True, blank=True, max_length=100, verbose_name='Общий полезный обьем')
    total_volume = CharField(null=True, blank=True, max_length=100, verbose_name='Общий обьем')
    useful_volume_refrigerator = CharField(null=True, blank=True, max_length=100, verbose_name='Общий полезный '
                                                                                                 'обьем холодильной '
                                                                                                 'камеры')
    volume_refrigerator = CharField(null=True, blank=True, max_length=100, verbose_name='Общий обьем холодильной '
                                                                                          'камеры')
    volume_freezer = CharField(null=True, blank=True, max_length=100, verbose_name='Объем морозильной камеры')
    useful_volume_freezer = CharField(null=True, blank=True, max_length=100, verbose_name='Полезный объем '
                                                                                            'морозильной камеры')
    weight = CharField(null=True, blank=True, max_length=100, verbose_name='Вес')
    height = CharField(null=True, blank=True, max_length=100, verbose_name='Высота')
    width = CharField(null=True, blank=True, max_length=100, verbose_name='Ширина')
    depth = CharField(null=True, blank=True, max_length=100, verbose_name='Глубина')
    dimensions = CharField(null=True, blank=True, max_length=100, verbose_name='Габариты (ВхГхШ)')
    package_height = CharField(null=True, blank=True, max_length=100, verbose_name='Высота упаковки')
    package_width = CharField(null=True, blank=True, max_length=100, verbose_name='Ширина упаковки')
    package_length = CharField(null=True, blank=True, max_length=100, verbose_name='Длина упаковки')
    climate_class = CharField(null=True, blank=True, max_length=100, verbose_name='Климатический класс')
    count_coolstore = CharField(null=True, blank=True, max_length=100, verbose_name='Количество камер')
    control_type = CharField(null=True, blank=True, max_length=100, verbose_name='Тип управления')
    inverter = CharField(null=True, blank=True, max_length=100, verbose_name='Инверторный')
    coating_material = CharField(null=True, blank=True, max_length=100, verbose_name='Материал покрытия')
    shelf_material = CharField(null=True, blank=True, max_length=100, verbose_name='Материал полок')
    autonomous_cold_storage = CharField(null=True, blank=True, max_length=100, verbose_name='Автономное сохранение '
                                                                                            'холода')
    antibacterial_coating = CharField(null=True, blank=True, max_length=100, verbose_name='Антибактериальное покрытие')
    ice_maker = CharField(null=True, blank=True, max_length=100, verbose_name='Генератор льда')
    child_protection = CharField(null=True, blank=True, max_length=100, verbose_name='Защита от детей')
    power_failure_indicator = CharField(null=True, blank=True, max_length=100, verbose_name='Индикация отключения '
                                                                                            'электропитания')
    holiday_mode = CharField(null=True, blank=True, max_length=100, verbose_name='Режим "Отпуск"')
    open_door_indicator = CharField(null=True, blank=True, max_length=100, verbose_name='Индикация открытой двери')
    temperature_increase_indicator = CharField(null=True, blank=True, max_length=100, verbose_name='Индикация '
                                                                                                   'повышения '
                                                                                                   'температуры')
    peculiarities = CharField(null=True, blank=True, max_length=100, verbose_name='Особенности')
    guarantee = CharField(null=True, blank=True, max_length=100, verbose_name='Гарантия')
    manufacturer = CharField(null=True, blank=True, max_length=100, verbose_name='Изготовитель')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Холодильник'
        verbose_name_plural = 'Холодильники'


class FridgeGrade(models.Model):
    negative_count = models.IntegerField(default=0)
    neutral_count = models.IntegerField(default=0)
    positive_count = models.IntegerField(default=0)
    total_grade = models.IntegerField(default=0)
    fridge = models.OneToOneField(Fridge, on_delete=models.CASCADE, primary_key=True)


class FridgeComment(models.Model):  # Комментарии
    text = models.TextField(null=True, blank=True, verbose_name='Содержание')
    fridge = models.ForeignKey(Fridge, on_delete=models.CASCADE, null=True)
    grade = models.IntegerField(null=True)

    def __str__(self):
        return f'Комментарий #{self.id}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class MobilePhone(models.Model):  # Мобильные телефоны
    title = models.TextField(blank=False, null=False, verbose_name='Название')
    img_url = models.TextField(null=True, blank=True, verbose_name='Ссылка на картинку')

    @property
    def fields(self):
        return [f.name for f in self._meta.fields + self._meta.many_to_many]

    def get_absolute_url(self):
        return reverse('mobile_phone', kwargs={'_id': self.pk})

    @property
    def fields_verbose(self):
        return dict([(f.name, f.verbose_name) for f in self._meta.fields + self._meta.many_to_many])

    # Характеристики
    screen_matrix_type = CharField(null=True, blank=True, max_length=100, verbose_name='Тип матрицы экрана')
    screen_diagonal = CharField(null=True, blank=True, max_length=100, verbose_name='Диагональ экрана')
    touch_screen = CharField(null=True, blank=True, max_length=100, verbose_name='Сенсорный экран')
    camera = CharField(null=True, blank=True, max_length=100, verbose_name='Фотокамера')
    camera_resolution = CharField(null=True, blank=True, max_length=100, verbose_name='Разрешение фотокамеры')
    front_camera = CharField(null=True, blank=True, max_length=100, verbose_name='Фронтальная камера')
    battery_capacity = CharField(null=True, blank=True, max_length=100, verbose_name='Емкость аккумулятора')
    organizer_calendar = CharField(null=True, blank=True, max_length=100, verbose_name='Органайзер/календарь')
    computer_synchronization = CharField(null=True, blank=True, max_length=100, verbose_name='Синхронизация с компьютером')
    calculator = CharField(null=True, blank=True, max_length=100, verbose_name='Калькулятор')
    weight = CharField(null=True, blank=True, max_length=100, verbose_name='Вес')
    height = CharField(null=True, blank=True, max_length=100, verbose_name='Высота')
    thickness = CharField(null=True, blank=True, max_length=100, verbose_name='Толщина')
    width = CharField(null=True, blank=True, max_length=100, verbose_name='Ширина')
    talk_time = CharField(null=True, blank=True, max_length=100, verbose_name='Время разговора')
    builtin_memory = CharField(null=True, blank=True, max_length=100, verbose_name='Объем встроенной памяти')
    memory_card_slot = CharField(null=True, blank=True, max_length=100, verbose_name='Слот для карты памяти')
    memory_card_type = CharField(null=True, blank=True, max_length=100, verbose_name='Тип карты памяти')
    max_memory_card_size = CharField(null=True, blank=True, max_length=100, verbose_name='Максимальный объем карты памяти')
    gsm = CharField(null=True, blank=True, max_length=100, verbose_name='GSM')
    three_g_support = CharField(null=True, blank=True, max_length=100, verbose_name='Поддержка 3G (UMTS)')
    wi_fi = CharField(null=True, blank=True, max_length=100, verbose_name='Wi-Fi')
    bluetooth = CharField(null=True, blank=True, max_length=100, verbose_name='Стандарт Bluetooth')
    usb_interface = CharField(null=True, blank=True, max_length=100, verbose_name='Интерфейс USB')
    headphone_output = CharField(null=True, blank=True, max_length=100, verbose_name='Выход на наушники')
    sos = CharField(null=True, blank=True, max_length=100, verbose_name='Наличие кнопки SOS')
    manufacturer = CharField(null=True, blank=True, max_length=100, verbose_name='Изготовитель')
    guarantee = CharField(null=True, blank=True, max_length=100, verbose_name='Гарантия')
    peculiarities = CharField(null=True, blank=True, max_length=100, verbose_name='Объем встроенной памяти')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Мобильный телефон'
        verbose_name_plural = 'Мобильные телефоны'


class MobilePhoneGrade(models.Model):
    negative_count = models.IntegerField(default=0)
    neutral_count = models.IntegerField(default=0)
    positive_count = models.IntegerField(default=0)
    total_grade = models.IntegerField(default=0)
    phone = models.OneToOneField(MobilePhone, on_delete=models.CASCADE, primary_key=True)


class MobilePhoneComment(models.Model):  # Комментарии
    text = models.TextField(null=True, blank=True, verbose_name='Содержание')
    phone = models.ForeignKey(MobilePhone, on_delete=models.CASCADE, null=True)
    grade = models.IntegerField(null=True)

    def __str__(self):
        return f'Комментарий #{self.id}'

    class Meta:
        verbose_name = 'Комментарий'

main/views.py
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import render
from django.db.models import Q
from main.models import Fridge, MobilePhone, Multicooker


def search(request):
    results = []
    q = request.GET.get('query').capitalize()
    if q:
        fridges = Fridge.objects.filter(Q(title__icontains=q))[:5]
        mobile_phones = MobilePhone.objects.filter(Q(title__icontains=q))[:5]
        multicookers = Multicooker.objects.filter(Q(title__icontains=q))[:5]
        results.extend([{'name': fridge.title, 'url': fridge.get_absolute_url()} for fridge in fridges])
        results.extend([{'name': mobile_phone.title, 'url': mobile_phone.get_absolute_url()} for mobile_phone in mobile_phones])
        results.extend([{'name': cooker.title, 'url': cooker.get_absolute_url()} for cooker in multicookers])

    return JsonResponse(results, safe=False)


def page_not_found(request, exception):
    return HttpResponseNotFound('<h1>Not Found</h1>')


def main(request):
    fridges = Fridge.objects.all()
    n_col = int(fridges.count() / 6)
    title = 'Главная страница'
    return render(request, 'main/main.html', locals())


def fridge(request, _id):
    fridge = Fridge.objects.get(id=_id)
    title = fridge.title
    return render(request, 'fridge/fridge.html', locals())


def mobile_phone(request, _id):
    phone = MobilePhone.objects.get(id=_id)
    title = phone.title
    return render(request, 'mobile_phone/mobile_phone.html', locals())


def multicooker(request, _id):
    multicooker = Multicooker.objects.get(id=_id)
    title = multicooker.title
    return render(request, 'multicooker/multicooker.html', locals())


def mobile_phones(request):
    mobile_phones = MobilePhone.objects.all()
    n_col = int(mobile_phones.count() / 6)
    title = 'Мобильные телефоны'
    return render(request, 'mobile_phone/mobile_phones.html', locals())


def multicookers(request):
    multicookers = Multicooker.objects.all()
    n_col = int(multicookers.count() / 6)
    title = 'Мультиварки'
    return render(request, 'multicooker/multicookers.html', locals())

templates/main/main.html
{% extends 'base.html' %}
{% load chunk_list %}
{% block content %}
    <div class="main-1920">

        <div class="filter">
            <div class="frame-8">
                <div>
                    <div class="chips-active"><a href="{% url 'main' %}"><p class="vse">Холодильники</p></a></div>
                </div>
                <div>
                    <div class="chips"><a href="{% url 'mobile_phones' %}"><p class="dlja-doma">Мобильные телефоны</p></a></div>
                </div>
                <div>
                    <div class="chips"><a href="{% url 'multicookers' %}"><p class="dlja-doma">Мультиварки</p></a></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Компьютеры</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Для красоты и здоровья</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Связь</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Автотехника</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Для ремонта</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Разное</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Фото и видео</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Для сада</p></div>
                </div>
            </div>
        </div>
        <div class="frame-9">
            {% with fridges|chunk_list:6 as cols %}
                {% for col in cols %}
                    <div class="frame-5">
                        {% for fridge in col %}
                            <div class="card">
                                <div class="frame-4">
                                    <div class="frame-2">
                                        <div class="frame-1">
                                            <img
                                                    alt=""
                                                    class="product-image"
                                                    src={{ fridge.img_url }}
                                            />
                                            <p class="holodil-nik-indesit-its-4180-w">
                                                {{ fridge.title }}
                                            </p>
                                        </div>
                                        <div class="frame-3">
                                            <div class="metadata">
                                                {% if fridge.fridgegrade.total_grade == 0 %}
                                                    <div class="star tooltip">
                                                        <img alt="" class="vector" src="/media/png/rejected.png"/>
                                                        <p class="tooltiptext">Медаль без оценки: товар, не имеющий
                                                            отзывов</p>
                                                    </div>
                                                {% endif %}
                                                {% if fridge.fridgegrade.total_grade <= 50 and fridge.fridgegrade.total_grade > 0 %}
                                                    <div class="star tooltip">
                                                        <img alt="" class="vector" src="/media/png/bronze-medal.png"/>
                                                        <p class="tooltiptext">Бронзовая медаль: товар имеет приемлемое
                                                            кол-во очков рейтинга, которых считается на основе
                                                            количества позитивных, негативных и нейтральных отзывов</p>
                                                    </div>
                                                {% endif %}
                                                {% if fridge.fridgegrade.total_grade <= 90 and fridge.fridgegrade.total_grade > 50 %}
                                                    <div class="star tooltip">
                                                        <img alt="" class="vector" src="/media/png/silver-medal.png"/>
                                                        <p class="tooltiptext">Серебрянная медаль: товар имеет достойное
                                                            кол-во очков рейтинга, которых считается на основе
                                                            количества позитивных, негативных и нейтральных отзывов</p>
                                                    </div>
                                                {% endif %}
                                                {% if fridge.fridgegrade.total_grade > 90 %}
                                                    <div class="star tooltip">
                                                        <img alt="" class="vector tooltiptext"
                                                             src="/media/png/gold-medal.png"/>
                                                        <p class="tooltiptext">Золотая медаль: товар имеет очень большое
                                                            кол-во очков рейтинга, которых считается на основе
                                                            количества позитивных, негативных и нейтральных отзывов</p>
                                                    </div>
                                                {% endif %}
                                            </div>
                                            <p class="num-21-otzyv">{{ fridge.fridgecomment_set.count }} отзыв</p>
                                        </div>
                                    </div>
                                    <div class="search-button">
                                        <a href="{% url 'fridge' fridge.id %} ">
                                            <p class="posmotret-otzyv">Посмотреть оценку</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            {% endwith %}
        </div>
    </div>
{% endblock %}

templates/main/search_results.html
<div class="search-answer">
{% for result in results %}
    <!-- Выводите информацию о каждом результате поиска -->
    <p>{{ result.name }}</p>
{% empty %}
    <p>Нет результатов поиска</p>
{% endfor %}
</div>