diplom_work/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found
from django.conf.urls.static import static

from diplom_work import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]
handler404 = page_not_found

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', main, name='main'),
    path('multicookers', multicookers, name='multicookers'),
    path('mobile_phones', mobile_phones, name='mobile_phones'),
    path('fridge/<int:_id>/', fridge, name='fridge'),
    path('mobile_phone/<int:_id>/', mobile_phone, name='mobile_phone'),
    path('multicooker/<int:_id>/', multicooker, name='multicooker'),
    path('search/', search, name='search'),
    ]

main/models.py
from django.db import models
from django.db.models import CharField
from django.urls import reverse


class Fridge(models.Model):  # Холодильники
    title = models.TextField(blank=False, null=False, verbose_name='Название')
    img_url = models.TextField(null=True, blank=True, verbose_name='Ссылка на картинку')

    # Характеристики
    @property
    def fields(self):
        return [f.name for f in self._meta.fields + self._meta.many_to_many]

    def get_absolute_url(self):
        return reverse('fridge', kwargs={'_id': self.pk})

    @property
    def fields_verbose(self):
        return dict([(f.name, f.verbose_name) for f in self._meta.fields + self._meta.many_to_many])
    total_useful_volume = CharField(null=True, blank=True, max_length=100, verbose_name='Общий полезный обьем')
    total_volume = CharField(null=True, blank=True, max_length=100, verbose_name='Общий обьем')
    useful_volume_refrigerator = CharField(null=True, blank=True, max_length=100, verbose_name='Общий полезный '
                                                                                                 'обьем холодильной '
                                                                                                 'камеры')
    volume_refrigerator = CharField(null=True, blank=True, max_length=100, verbose_name='Общий обьем холодильной '
                                                                                          'камеры')
    volume_freezer = CharField(null=True, blank=True, max_length=100, verbose_name='Объем морозильной камеры')
    useful_volume_freezer = CharField(null=True, blank=True, max_length=100, verbose_name='Полезный объем '
                                                                                            'морозильной камеры')
    weight = CharField(null=True, blank=True, max_length=100, verbose_name='Вес')
    height = CharField(null=True, blank=True, max_length=100, verbose_name='Высота')
    width = CharField(null=True, blank=True, max_length=100, verbose_name='Ширина')
    depth = CharField(null=True, blank=True, max_length=100, verbose_name='Глубина')
    dimensions = CharField(null=True, blank=True, max_length=100, verbose_name='Габариты (ВхГхШ)')
    package_height = CharField(null=True, blank=True, max_length=100, verbose_name='Высота упаковки')
    package_width = CharField(null=True, blank=True, max_length=100, verbose_name='Ширина упаковки')
    package_length = CharField(null=True, blank=True, max_length=100, verbose_name='Длина упаковки')
    climate_class = CharField(null=True, blank=True, max_length=100, verbose_name='Климатический класс')
    count_coolstore = CharField(null=True, blank=True, max_length=100, verbose_name='Количество камер')
    control_type = CharField(null=True, blank=True, max_length=100, verbose_name='Тип управления')
    inverter = CharField(null=True, blank=True, max_length=100, verbose_name='Инверторный')
    coating_material = CharField(null=True, blank=True, max_length=100, verbose_name='Материал покрытия')
    shelf_material = CharField(null=True, blank=True, max_length=100, verbose_name='Материал полок')
    autonomous_cold_storage = CharField(null=True, blank=True, max_length=100, verbose_name='Автономное сохранение '
                                                                                            'холода')
    antibacterial_coating = CharField(null=True, blank=True, max_length=100, verbose_name='Антибактериальное покрытие')
    ice_maker = CharField(null=True, blank=True, max_length=100, verbose_name='Генератор льда')
    child_protection = CharField(null=True, blank=True, max_length=100, verbose_name='Защита от детей')
    power_failure_indicator = CharField(null=True, blank=True, max_length=100, verbose_name='Индикация отключения '
                                                                                            'электропитания')
    holiday_mode = CharField(null=True, blank=True, max_length=100, verbose_name='Режим "Отпуск"')
    open_door_indicator = CharField(null=True, blank=True, max_length=100, verbose_name='Индикация открытой двери')
    temperature_increase_indicator = CharField(null=True, blank=True, max_length=100, verbose_name='Индикация '
                                                                                                   'повышения '
                                                                                                   'температуры')
    peculiarities = CharField(null=True, blank=True, max_length=100, verbose_name='Особенности')
    guarantee = CharField(null=True, blank=True, max_length=100, verbose_name='Гарантия')
    manufacturer = CharField(null=True, blank=True, max_length=100, verbose_name='Изготовитель')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Холодильник'
        verbose_name_plural = 'Холодильники'


class FridgeGrade(models.Model):
    negative_count = models.IntegerField(default=0)
    neutral_count = models.IntegerField(default=0)
    positive_count = models.IntegerField(default=0)
    total_grade = models.IntegerField(default=0)
    fridge = models.OneToOneField(Fridge, on_delete=models.CASCADE, primary_key=True)


class FridgeComment(models.Model):  # Комментарии
    text = models.TextField(null=True, blank=True, verbose_name='Содержание')
    fridge = models.ForeignKey(Fridge, on_delete=models.CASCADE, null=True)
    grade = models.IntegerField(null=True)

    def __str__(self):
        return f'Комментарий #{self.id}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class MobilePhone(models.Model):  # Мобильные телефоны
    title = models.TextField(blank=False, null=False, verbose_name='Название')
    img_url = models.TextField(null=True, blank=True, verbose_name='Ссылка на картинку')

    @property
    def fields(self):
        return [f.name for f in self._meta.fields + self._meta.many_to_many]

    def get_absolute_url(self):
        return reverse('mobile_phone', kwargs={'_id': self.pk})

    @property
    def fields_verbose(self):
        return dict([(f.name, f.verbose_name) for f in self._meta.fields + self._meta.many_to_many])

    # Характеристики
    screen_matrix_type = CharField(null=True, blank=True, max_length=100, verbose_name='Тип матрицы экрана')
    screen_diagonal = CharField(null=True, blank=True, max_length=100, verbose_name='Диагональ экрана')
    touch_screen = CharField(null=True, blank=True, max_length=100, verbose_name='Сенсорный экран')
    camera = CharField(null=True, blank=True, max_length=100, verbose_name='Фотокамера')
    camera_resolution = CharField(null=True, blank=True, max_length=100, verbose_name='Разрешение фотокамеры')
    front_camera = CharField(null=True, blank=True, max_length=100, verbose_name='Фронтальная камера')
    battery_capacity = CharField(null=True, blank=True, max_length=100, verbose_name='Емкость аккумулятора')
    organizer_calendar = CharField(null=True, blank=True, max_length=100, verbose_name='Органайзер/календарь')
    computer_synchronization = CharField(null=True, blank=True, max_length=100, verbose_name='Синхронизация с компьютером')
    calculator = CharField(null=True, blank=True, max_length=100, verbose_name='Калькулятор')
    weight = CharField(null=True, blank=True, max_length=100, verbose_name='Вес')
    height = CharField(null=True, blank=True, max_length=100, verbose_name='Высота')
    thickness = CharField(null=True, blank=True, max_length=100, verbose_name='Толщина')
    width = CharField(null=True, blank=True, max_length=100, verbose_name='Ширина')
    talk_time = CharField(null=True, blank=True, max_length=100, verbose_name='Время разговора')
    builtin_memory = CharField(null=True, blank=True, max_length=100, verbose_name='Объем встроенной памяти')
    memory_card_slot = CharField(null=True, blank=True, max_length=100, verbose_name='Слот для карты памяти')
    memory_card_type = CharField(null=True, blank=True, max_length=100, verbose_name='Тип карты памяти')
    max_memory_card_size = CharField(null=True, blank=True, max_length=100, verbose_name='Максимальный объем карты памяти')
    gsm = CharField(null=True, blank=True, max_length=100, verbose_name='GSM')
    three_g_support = CharField(null=True, blank=True, max_length=100, verbose_name='Поддержка 3G (UMTS)')
    wi_fi = CharField(null=True, blank=True, max_length=100, verbose_name='Wi-Fi')
    bluetooth = CharField(null=True, blank=True, max_length=100, verbose_name='Стандарт Bluetooth')
    usb_interface = CharField(null=True, blank=True, max_length=100, verbose_name='Интерфейс USB')
    headphone_output = CharField(null=True, blank=True, max_length=100, verbose_name='Выход на наушники')
    sos = CharField(null=True, blank=True, max_length=100, verbose_name='Наличие кнопки SOS')
    manufacturer = CharField(null=True, blank=True, max_length=100, verbose_name='Изготовитель')
    guarantee = CharField(null=True, blank=True, max_length=100, verbose_name='Гарантия')
    peculiarities = CharField(null=True, blank=True, max_length=100, verbose_name='Объем встроенной памяти')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Мобильный телефон'
        verbose_name_plural = 'Мобильные телефоны'


class MobilePhoneGrade(models.Model):
    negative_count = models.IntegerField(default=0)
    neutral_count = models.IntegerField(default=0)
    positive_count = models.IntegerField(default=0)
    total_grade = models.IntegerField(default=0)
    phone = models.OneToOneField(MobilePhone, on_delete=models.CASCADE, primary_key=True)


class MobilePhoneComment(models.Model):  # Комментарии
    text = models.TextField(null=True, blank=True, verbose_name='Содержание')
    phone = models.ForeignKey(MobilePhone, on_delete=models.CASCADE, null=True)
    grade = models.IntegerField(null=True)

    def __str__(self):
        return f'Комментарий #{self.id}'

    class Meta:
        verbose_name = 'Комментарий'

templates/mobile_phone/mobile_phone.html
{% extends 'base.html' %}
{% load calc_percents %}
{% load get_verbose_name %}
{% block content %}
    <div class="bg">

        <div class="card-main">
            <div class="header-card">
                <div class="rewiew-div">
                    <img
                            alt=""
                            class="prod-image"
                            src={{ phone.img_url }}
                    />
                </div>
                <div class="grade-div">
                    <div class="title-card">
                    <span class="tooltip-icon">?</span>
                            <div class="tooltip-icon-text">Наведите на медаль для отображения доп.информации</div>
                        <p class="prod-title">{{ phone.title }}</p>
                        <div class="comment-count">
                            {% if phone.mobilephonegrade.total_grade == 0 %}
                                <div class="star tooltip">
                                    <img alt="" class="vector" src="/media/png/rejected.png"/>
                                    <p class="tooltiptext">Медаль без оценки: товар, не имеющий отзывов</p>
                                </div>
                            {% endif %}
                            {% if phone.mobilephonegrade.total_grade <= 50 and phone.mobilephonegrade.total_grade > 0 %}
                                <div class="star tooltip">
                                    <img alt="" class="vector" src="/media/png/bronze-medal.png"/>
                                    <p class="tooltiptext">Бронзовая медаль: товар имеет приемлемое кол-во очков рейтинга, которых считается на основе количества позитивных, негативных и нейтральных отзывов</p>
                                </div>
                            {% endif %}
                            {% if phone.mobilephonegrade.total_grade <= 90 and phone.mobilephonegrade.total_grade > 50 %}
                                <div class="star tooltip">
                                    <img alt="" class="vector" src="/media/png/silver-medal.png"/>
                                    <p class="tooltiptext">Серебрянная медаль: товар имеет достойное кол-во очков рейтинга, которых считается на основе количества позитивных, негативных и нейтральных отзывов</p>
                                </div>
                            {% endif %}
                            {% if phone.mobilephonegrade.total_grade > 90 %}
                                <div class="star tooltip">
                                    <img alt="" class="vector tooltiptext" src="/media/png/gold-medal.png"/>
                                    <p class="tooltiptext">Золотая медаль: товар имеет очень большое кол-во очков рейтинга, которых считается на основе количества позитивных, негативных и нейтральных отзывов</p>
                                </div>
                            {% endif %}
                            <p class="num-21-otzyv">{{ phone.mobilephonecomment_set.count }} отзыв</p>
                        </div>
                    </div>
                    <div class="bar-title">Статистика отзывов</div>
                    <div class="bar-chart">
                            <span class="tooltip-icon">?</span>
                            <div class="tooltip-icon-text">Наведите на столбцы графика для отображения доп. информации</div>
                            <div>
                            <div class="bar tooltip" style="background-color: green;  height: calc({{ phone.mobilephonegrade.positive_count }} * 10px);">
                                <p class="tooltiptext">Положительные отзывы:{% calc_percents  phone.mobilephonecomment_set.count  phone.mobilephonegrade.positive_count %}%</p>
                            </div>
                                <span class="bar-span">{{ phone.mobilephonegrade.positive_count }}</span>
                                </div>
                            <div>
                            <div class="bar tooltip" style="background-color: grey;  height: calc({{ phone.mobilephonegrade.neutral_count }} * 10px);">
                                <p class="tooltiptext">Нейтральные отзывы:{% calc_percents phone.mobilephonecomment_set.count  phone.mobilephonegrade.neutral_count %}%</p>
                            </div>
                                <span class="bar-span">{{ phone.mobilephonegrade.neutral_count }}</span>
                                </div>
                            <div>
                            <div class="bar tooltip" style="background-color: red;  height: calc({{ phone.mobilephonegrade.negative_count }} * 10px);">
                                <p class="tooltiptext">Негативные отзывы:{% calc_percents phone.mobilephonecomment_set.count  phone.mobilephonegrade.negative_count %}%</p>
                            </div>
                                <span class="bar-span">{{ phone.mobilephonegrade.negative_count }}</span>
                                </div>
                    </div>
                </div>
            </div>
            <div class="footer-card">
                <div style="margin-left: 20px;min-width: 500px; border-right: 1px solid lightgrey;padding-right: 20px;">
                    <div class="comment-header">
                        <span class="comment-title-span">Отзывы</span>
                        <span class="comment-count-span">{{ phone.mobilephonecomment_set.count }} </span>
                    </div>
                    {% for c in phone.mobilephonecomment_set.all %}
                        <div class="comment-div">
                            <div class="comment-title">Автор</div>
                            <div class="comment-text">Отзыв</div>
                            <span>{{ c.text }}</span>
                            <div class="comment-title">Оценка</div>
                            {% if c.grade == 0 %}
                                <span style="color:grey">Нейтральная</span>
                            {% elif c.grade == 1 %}
                                <span style="color:green">Положительная</span>
                            {% elif c.grade == 2 %}
                                <span style="color:red">Отрицательная</span>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="characteristics-div">
                    <div class="comment-header">
                        <span class="comment-title-span">Характеристики</span>
                    </div>
                    {% if phone.screen_matrix_type %}
                        <div class="characteristics-item">
                            <span>{% get_verbose_field_name phone "screen_matrix_type" %}</span>
                            <span class="characteristics-span">{{ phone.screen_matrix_type }}</span>
                        </div>
                    {% endif %}
                    {% if phone.screen_diagonal %}
                        <div class="characteristics-item">
                            <span>{% get_verbose_field_name phone "screen_diagonal" %}</span>
                            <span class="characteristics-span">{{ phone.screen_diagonal }}</span>
                        </div>
                    {% endif %}
                    {% if phone.touch_screen %}
                        <div class="characteristics-item">
                            <span>{% get_verbose_field_name phone "touch_screen" %}</span>
                            <span class="characteristics-span">{{ phone.touch_screen }}</span>
                        </div>
                    {% endif %}
                    {% if phone.camera %}
                        <div class="characteristics-item">
                            <span>{% get_verbose_field_name phone "camera" %}</span>
                            <span class="characteristics-span">{{ phone.camera }}</span>
                        </div>
                    {% endif %}
                    {% if phone.camera_resolution %}
                        <div class="characteristics-item">
                            <span>{% get_verbose_field_name phone "camera_resolution" %}</span>
                            <span class="characteristics-span">{{ phone.camera_resolution }}</span>
                        </div>
                    {% endif %}
                    {% if phone.front_camera %}
                        <div class="characteristics-item">
                            <span>{% get_verbose_field_name phone "front_camera" %}</span>
                            <span class="characteristics-span">{{ phone.front_camera }}</span>
                        </div>
                    {% endif %}
                    {% if phone.battery_capacity %}
                        <div class="characteristics-item">
                            <span>{% get_verbose_field_name phone "battery_capacity" %}</span>
                            <span class="characteristics-span">{{ phone.battery_capacity }}</span>
                        </div>
                    {% endif %}
                    {% if phone.organizer_calendar %}
                        <div class="characteristics-item">
                            <span>{% get_verbose_field_name phone "organizer_calendar" %}</span>
                            <span class="characteristics-span">{{ phone.organizer_calendar }}</span>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/mobile_phone/mobile_phones.html
{% extends 'base.html' %}
{% load chunk_list %}
{% block content %}
    <div class="main-1920">
        <div class="filter">
            <div class="frame-8">
                <div>
                    <div class="chips"><a href="{% url 'main' %}"><p class=dlja-doma">Холодильники</p></a></div>
                </div>
                <div>
                    <div class="chips-active"><a href="{% url 'mobile_phones' %}"><p class="vse">Мобильные телефоны</p></a></div>
                </div>
                <div>
                    <div class="chips"><a href="{% url 'multicookers' %}"><p class="dlja-doma">Мультиварки</p></a></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Компьютеры</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Для красоты и здоровья</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Связь</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Автотехника</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Для ремонта</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Разное</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Фото и видео</p></div>
                </div>
                <div>
                    <div class="chips"><p class="dlja-doma">Для сада</p></div>
                </div>
            </div>
        </div>
        <div class="frame-9">
            {% with mobile_phones|chunk_list:6 as cols %}
                {% for col in cols %}
                    <div class="frame-5">
                        {% for mobilephone in col %}
                            <div class="card">
                                <div class="frame-4">
                                    <div class="frame-2">
                                        <div class="frame-1">
                                            <img
                                                    alt=""
                                                    class="product-image"
                                                    src={{ mobilephone.img_url }}
                                            />
                                            <p class="holodil-nik-indesit-its-4180-w">
                                                {{ mobilephone.title }}
                                            </p>
                                        </div>
                                        <div class="frame-3">
                                            <div class="metadata">
                                                {% if mobilephone.mobilephonegrade.total_grade == 0 %}
                                                    <div class="star tooltip">
                                                        <img alt="" class="vector" src="/media/png/rejected.png"/>
                                                        <p class="tooltiptext">Медаль без оценки: товар, не имеющий
                                                            отзывов</p>
                                                    </div>
                                                {% endif %}
                                                {% if mobilephone.mobilephonegrade.total_grade <= 50 and mobilephone.mobilephonegrade.total_grade > 0 %}
                                                    <div class="star tooltip">
                                                        <img alt="" class="vector" src="/media/png/bronze-medal.png"/>
                                                        <p class="tooltiptext">Бронзовая медаль: товар имеет приемлемое
                                                            кол-во очков рейтинга, которых считается на основе
                                                            количества позитивных, негативных и нейтральных отзывов</p>
                                                    </div>
                                                {% endif %}
                                                {% if mobilephone.mobilephonegrade.total_grade <= 90 and mobilephone.mobilephonegrade.total_grade > 50 %}
                                                    <div class="star tooltip">
                                                        <img alt="" class="vector" src="/media/png/silver-medal.png"/>
                                                        <p class="tooltiptext">Серебрянная медаль: товар имеет достойное
                                                            кол-во очков рейтинга, которых считается на основе
                                                            количества позитивных, негативных и нейтральных отзывов</p>
                                                    </div>
                                                {% endif %}
                                                {% if mobilephone.mobilephonegrade.total_grade > 90 %}
                                                    <div class="star tooltip">
                                                        <img alt="" class="vector tooltiptext"
                                                             src="/media/png/gold-medal.png"/>
                                                        <p class="tooltiptext">Золотая медаль: товар имеет очень большое
                                                            кол-во очков рейтинга, которых считается на основе
                                                            количества позитивных, негативных и нейтральных отзывов</p>
                                                    </div>
                                                {% endif %}
                                            </div>
                                            <p class="num-21-otzyv">{{ mobilephone.mobilephonecomment_set.count }} отзыв</p>
                                        </div>
                                    </div>
                                    <div class="search-button">
                                        <a href="{% url 'mobile_phone' mobilephone.id %} ">
                                            <p class="posmotret-otzyv">Посмотреть оценку</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            {% endwith %}
        </div>
    </div>
{% endblock %}